planner_configs:
  SBLkConfigDefault:
    type: geometric::SBL
  LBKPIECEkConfigDefault:
    type: geometric::LBKPIECE
  RRTkConfigDefault:
    type: geometric::RRT
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
  LazyRRTkConfigDefault:
    type: geometric::LazyRRT
  ESTkConfigDefault:
    type: geometric::EST
  KPIECEkConfigDefault:
    type: geometric::KPIECE
  RRTStarkConfigDefault:
    type: geometric::RRTstar
  BKPIECEkConfigDefault:
    type: geometric::BKPIECE
arm:
  planner_configs:
    - SBLkConfigDefault
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - LazyRRTkConfigDefault
    - ESTkConfigDefault
    - KPIECEkConfigDefault
    - RRTStarkConfigDefault
    - BKPIECEkConfigDefault
  projection_evaluator: joints(iri_wam_joint_1,iri_wam_joint_2)
  longest_valid_segment_fraction: 0.005
arm_gripper:
  planner_configs:
    - SBLkConfigDefault
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - LazyRRTkConfigDefault
    - ESTkConfigDefault
    - KPIECEkConfigDefault
    - RRTStarkConfigDefault
    - BKPIECEkConfigDefault
